src/ApiBundle/Entity/Profile.php
<?php

namespace ApiBundle\Entity;

use AppBundle\Entity\Person;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * Class Profile
 * @package ApiBundle\Entity
 */
class Profile
{
    // lunch time
    public const LUNCH_START_TIME = '12:00';
    public const LUNCH_END_TIME = '14:00';

    // default password
    public const DEFAULT_PASSWORD = 'PleaseChangeMe';

    /**
     * @var int
     */
    private $id;

    /**
     * @var text|null
     */

    private $workingHours;

    /**
     * @var DateTime
     */
    private $lunchStartTime;

    /**
     * @var DateTime
     */
    private $lunchEndTime;

    /**
     * @var DateTime
     */
    private $creationDate;

    /**
     * @var DateTime
     */
    private $updateDate;

    /**
     * @var string
     */
    private $firstName;

    /**
     * @var string
     */
    private $lastName;

    /**
     * @var string|null
     */
    private $fixedPhone;

    /**
     * @var string|null
     */
    private $mobilePhone;

    /**
     * @var string|null
     */
    private $employeeId;

    /**
     * @var string|null
     */
    private $otherEmail;

    /**
     * @var string
     */
    private $billingCode;

    /**
     * @var string
     */
    private $number;

    /**
     * @var string
     */
    private $street;

    /**
     * @var string
     */
    private $district;

    /**
     * @var string
     */
    private $city;

    /**
     * @var string
     */
    private $region;

    /**
     * @var string|null
     */
    private $avatar;

    /**
     * @var string|null
     */
    private $organisationRegistrationNumber;

    /**
     * @var string|null
     */
    private $pitch;

    /**
     * @var string|null
     */
    private $video;

    /**
     * @var string|null
     */
    private $curriculumVitae;

    /**
     * @var string|null
     */
    private $scannedIban;

    /**
     * @var string|null
     */
    private $iban;

    /**
     * @var string|null
     */
    private $cv;

    /**
     * @var string|null
     */
    private $bicCode;

    /**
     * @var Person
     */
    private $person;

    /**
     * @var CompanyPost
     */
    private $companyPost;

    /**
     * @var RestrictionAccess
     */
    private $restrictionAccess;

    /**
     * @var Entity
     */
    private $entity;

    /**
     * @var ProfileVariety
     */
    private $profileType;

    /**
     * @var LiveResourceOrigin
     */
    private $liveResourceOrigin;

    /**
     * @var InterventionPerimeter
     */
    private $interventionPerimeter;

    /**
     * @var Collection
     */
    private $manager;

    /**
     * @var Collection
     */
    private $attendanceAttestation;

    private $billingAddress;

    private $noteGlobal;

    private $nbActivitiesExecuted;

    /**
     * @var Regional
     */
    private $regional;

    /**
     * @var GroupOrganization
     */
    private $groupOrganization;

    /**
     * @var Workplace
     */
    private $workplace;

    /**
     * @var string|null
     */
    private $bankName;

    /**
     * @var string|null
     */
    private $accountCurrency;

    /**
     * @var string|null
     */
    private $bic;

    /**
     * @var string|null
     */
    private $bankCode;

    /**
     * @var string|null
     */
    private $agencyCode;

    /**
     * @var string|null
     */
    private $accountNum;

    /**
     * @var string|null
     */
    private $ribKey;

    /**
     * @var string|null
     */
    private $domiciliationAgency;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->manager               = new ArrayCollection();
        $this->attendanceAttestation = new ArrayCollection();
    }

    /**
     * @return InterventionPerimeter
     */
    public function getInterventionPerimeter()
    {
        return $this->interventionPerimeter;
    }

    /**
     * @param InterventionPerimeter $interventionPerimeter
     */
    public function setInterventionPerimeter(InterventionPerimeter $interventionPerimeter = null)
    {
        $this->interventionPerimeter = $interventionPerimeter;
        return $this;
    }


    /**
     * @return LiveResourceOrigin
     */
    public function getLiveResourceOrigin()
    {
        return $this->liveResourceOrigin;
    }

    /**
     * @param LiveResourceOrigin $liveResourceOrigin
     */
    public function setLiveResourceOrigin(LiveResourceOrigin $liveResourceOrigin = null)
    {
        $this->liveResourceOrigin = $liveResourceOrigin;
        return $this;
    }


    /**
     * @return null|string
     */
    public function getBankName()
    {
        return $this->bankName;
    }

    /**
     * @param null|string $bankName
     */
    public function setBankName($bankName = null)
    {
        $this->bankName = $bankName;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getAccountCurrency()
    {
        return $this->accountCurrency;
    }

    /**
     * @param null|string $accountCurrency
     */
    public function setAccountCurrency($accountCurrency = null)
    {
        $this->accountCurrency = $accountCurrency;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getBic()
    {
        return $this->bic;
    }

    /**
     * @param null|string $bic
     */
    public function setBic($bic = null)
    {
        $this->bic = $bic;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getBankCode()
    {
        return $this->bankCode;
    }

    /**
     * @param null|string $bankCode
     */
    public function setBankCode($bankCode = null)
    {
        $this->bankCode = $bankCode;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getAgencyCode()
    {
        return $this->agencyCode;
    }

    /**
     * @param null|string $agencyCode
     */
    public function setAgencyCode($agencyCode = null)
    {
        $this->agencyCode = $agencyCode;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getAccountNum()
    {
        return $this->accountNum;
    }

    /**
     * @param null|string $accountNum
     */
    public function setAccountNum($accountNum = null)
    {
        $this->accountNum = $accountNum;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getRibKey()
    {
        return $this->ribKey;
    }

    /**
     * @param null|string $ribKey
     */
    public function setRibKey($ribKey = null)
    {
        $this->ribKey = $ribKey;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getDomiciliationAgency()
    {
        return $this->domiciliationAgency;
    }

    /**
     * @param null|string $domiciliationAgency
     */
    public function setDomiciliationAgency($domiciliationAgency = null)
    {
        $this->domiciliationAgency = $domiciliationAgency;
        return $this;
    }



    /**
     * @return GroupOrganization
     */
    public function getGroupOrganization()
    {
        return $this->groupOrganization;
    }

    /**
     * @param GroupOrganization $groupOrganization
     */
    public function setGroupOrganization(GroupOrganization $groupOrganization = null)
    {
        $this->groupOrganization = $groupOrganization;
        return $this;
    }

    /**
     * @return Regional
     */
    public function getRegional()
    {
        return $this->regional;
    }

    /**
     * @param Regional $regional
     */
    public function setRegional(Regional $regional = null)
    {
        $this->regional = $regional;
        return $this;
    }

    /**
     * @return Workplace
     */
    public function getWorkplace()
    {
        return $this->workplace;
    }

    /**
     * @param Workplace $workplace
     *
     * @return Profile
     */
    public function setWorkplace(Workplace $workplace = null)
    {
        $this->workplace = $workplace;

        return $this;
    }

    /**
     * @return text|null
     */
    public function getWorkingHours()
    {
        return unserialize($this->workingHours);
    }

    /**
     * @param text|null $workingHours
     */
    public function setWorkingHours($workingHours)
    {
        $this->workingHours = serialize($workingHours);
        return $this;
    }

    public function getDisplayName()
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get lunchStartTime.
     *
     * @return DateTime
     */
    public function getLunchStartTime()
    {
        return $this->lunchStartTime;
    }

    /**
     * Set lunchStartTime.
     *
     * @param DateTime $lunchStartTime
     *
     * @return Profile
     */
    public function setLunchStartTime($lunchStartTime)
    {
        $this->lunchStartTime = $lunchStartTime;

        return $this;
    }

    /**
     * Get lunchEndTime.
     *
     * @return DateTime
     */
    public function getLunchEndTime()
    {
        return $this->lunchEndTime;
    }

    /**
     * Set lunchEndTime.
     *
     * @param DateTime $lunchStartTime
     *
     * @return Profile
     */
    public function setLunchEndTime($lunchEndTime)
    {
        $this->lunchEndTime = $lunchEndTime;

        return $this;
    }

    /**
     * Set creationDate.
     *
     * @param DateTime $creationDate
     *
     * @return Profile
     */
    public function setCreationDate($creationDate)
    {
        $this->creationDate = $creationDate;

        return $this;
    }

    /**
     * Get creationDate.
     *
     * @return DateTime
     */
    public function getCreationDate()
    {
        return $this->creationDate;
    }

    /**
     * Set updateDate.
     *

templates/molecules/courses/animationold.html.twig
<link rel="stylesheet" href="{{ asset('js/lib/leaflet/leaflet.css') }}"/>
{% set status_done =  constant('ApiBundle\\Entity\\Status::WITH_BOOKING_DONE') %}
{% set status_learner_absent =  constant('ApiBundle\\Entity\\Status::WITH_BOOKING_LEARNER_ABSENT') %}
{% set myAddress = '14 Phan Ton, District 1 HCM City' %}
<div class="card card-pane" data-id="{{ module.id }}" data-start="{{ module.beginningWithTime|date('Y-m-d H:i:s') }}"
     data-end="{{ module.endingWithTime|date('Y-m-d H:i:s') }}">

    <div class="card-header card-header--module c-bg-lightblue">
        <h4><i class="fal fa-users marg-r-20"></i>{{ 'admin.interventions.mods.animation'|trans }}: <span class="font-weight-light">{{ module.designation }}</span></h4>
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a href="#agenda" class="nav-link {% if not isBooked %}active show{% endif %}" data-toggle="tab">
                    {{ 'learners.courses.agenda'|trans }}
                </a>
            </li>

            <li class="nav-item">
                <a href="#files" class="nav-link {% if isBooked %}active show{% endif %}" data-toggle="tab">
                    {{ 'learners.courses.my_session'|trans }}
                </a>
            </li>
        </ul>
    </div>

    <div class="card-body">
        <div class="tab-content tab-space">
            <div class="row">
                <div class="col-md-4">
                    <h3>{{ 'learners.courses.information'|trans|title }}</h3>
                    <div class="more">
                        <p class="c-black"> {{ module.description|raw }}</p>
                    </div>
                </div>

                <div class="col-md-4 border-right-custom border-left-custom">
                    <h3>{{ 'learners.courses.details'|trans|title }}</h3>
                    {% if not isBooked %}
                        {% include ':molecules/courses/classroomTraining:detail_available_molecule.html.twig' %}
                    {% else %}
                        {% include ':molecules/courses/classroomTraining:detail_booked_molecule.html.twig' %}
                    {% endif %}
                </div>

                <div class="col-md-4">
                    <h3>{{ 'learners.courses.documents'|trans|title }}</h3>
                    {% if module.educationalDocument|length != 0 %}
                        <div class="course-card">
                            {{ include('molecules/tables/files-list.html.twig', {documents: module.educationalDocument, type: "documents"}) }}
                        </div>
                    {% endif %}

                    {% if (booked.status is defined and booked.status is not null) and booked.status.id ==  status_done %}
                        <div class="row">
                            <h3>{{ 'learners.courses.report'|trans|capitalize }}</h3>
                            <div class="courseFilesList">
                                {% if booked.report.fileDescriptor is defined and booked.report.fileDescriptor is not null %}
                                    {{ include('molecules/tables/files-list.html.twig', {documents: [booked.report], type: "documents"}) }}
                                {% endif %}
                            </div>
                        </div>

                        <div class="row">
                            <div class="marg-t-20">
                                <h3>{{ 'learners.courses.grade'|trans|capitalize }}</h3>
                                <fieldset>
                                    {% set grade = booked.learnerGrade is not null ? booked.learnerGrade : 'learners.courses.awaiting_grade'|trans|capitalize %}
                                    <h4>{{ grade }}</h4>
                                </fieldset>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="tab-pane {% if not isBooked %}active hidden {% endif %}" id="agenda" data-target="calendar">
                {{ include('molecules/calendar/calendar-legend.twig', { user: 'learner' }) }}
                <div id="virtualClassCalendar" class="marg-t-20"></div>
            </div>

            <div class="tab-pane {% if isBooked %}active{% endif %}" id="files">

                <h2 class="courseHeader text-center">{{ module.designation }}</h2>
                <div class="row">
                    <div class="col-md-2">
                    </div>
                    <div class="col-md-8">
                        <div class="t-center">
                            {% if isBooked %}
                                {% if (expired) %}
                                    <p>{{ 'booking.expired'|trans }}</p>
                                {% elseif booked.moduleSession.sessionPlace %}
                                    {% set myAddress = booked.moduleSession.sessionPlace.address %}
                                    <div id="mapid" style="width: 100%; height: 600px; text-align: center;"></div>
                                {% endif %}
                            {% else %}
                                <p>{{ 'learners.courses.book_to_join_webinar'|trans }}</p>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-md-2">
                    </div>
                </div>

                {{ include('molecules/courses/navigation.html.twig') }}


                {% if canBeNotated%}
                    {{ include('molecules/courses/notation.html.twig') }}
                {% endif %}

            </div>
        </div>
    </div>

    {{ include('molecules/modal/book-classroom-trainning-modal.html.twig') }}

    <span id="cancel-booking-text" class="text-template">{{ 'learners.courses.cancel_booking'|trans }}</span>
    <span id="book-session-text" class="text-template">{{ 'learners.courses.book_session'|trans }}</span>

    {{ include('molecules/modal/cancel-confirmation-modal.html.twig') }}
</div>

{% block javascripts %}
    <script src="{{ asset('js/lib/leaflet/leaflet.js') }}"></script>
    <script src="{{ asset('js/learner/calendar-vclass.js') }}"></script>
    <script>
        if (document.getElementById('mapid')) {
            var address = '{{ myAddress }}';
            $.get(location.protocol + '//nominatim.openstreetmap.org/search?format=json&q=' + address, function(data){
                var latX = data[0].lat;
                var lonY = data[0].lon;
                var mymap = L.map('mapid').setView([latX, lonY], 13);

                L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(mymap);

                L.marker([latX, lonY]).addTo(mymap)
                    .bindPopup(address).openPopup();

                var popup = L.popup();

                function onMapClick(e) {
                    popup
                        .setLatLng(e.latlng)
                        .setContent("You clicked the map at " + e.latlng.toString())
                        .openOn(mymap);
                }

                mymap.on('click', onMapClick);
            });
        }
    </script>
{% endblock %}

templates/molecules/courses/exercice.html.twig
<div class="card-header card-header-icon">
    <div class="card-icon c-bg-orangelight">
        <i class="fal fa-video"></i>
    </div>
</div>

<div class="card-body">
    {% if module.subject and module.subject.designation %}
        <h4 class="text-center">{{ module.subject.designation }}</h4>
    {% endif %}
    <h5 class="text-center" style="margin-top: 25px;">
        {{ module.designation }}
    </h5>
    <p class="text-center">

    </p>

    <p class="text-right">
        <b>{{ 'global.from'|trans|capitalize }}</b> {{ module.beginning|date('Y-m-d') }}
        <b>{{ 'global.to'|trans }}</b> {{ module.ending|date('Y-m-d') }}
        <br>
        {{ 'booking.duration'|trans }} : {{ module.duration|date('i:s') }}
    </p>

    {% if module.mediaDocument %}
        <audio controls="controls">
            <source src="{{ asset('files/'~ module.mediaDocument.fileDescriptor.path) }}" type="audio/aac" />
        </audio>
    {% endif %}

    {{ include('molecules/courses/notation.html.twig') }}
    {{ include('molecules/courses/navigation.html.twig') }}

</div>

templates/molecules/courses/instructions.html.twig
    <p class="text-center ">
        <ul class="instruction">
          <li class="blue">seances already booked.</li>
          <li class="green">available slots for selected seance in the left panel</li>
          <li class="gray">complete sessions.</li>
        </ul>
        Choose your slot on the calendar, and clic to book.
    </p>

templates/molecules/courses/onlineseance.html.twig
{% set buttonTitle = isBooked ? "learners.buttons.change_date" : "learners.buttons.book_session" %}
{% set status_done =  constant('ApiBundle\\Entity\\Status::WITH_BOOKING_DONE') %}
{% set status_booked =  constant('ApiBundle\\Entity\\Status::WITH_BOOKING_BOOKED') %}
{% set status_absent =  constant('ApiBundle\\Entity\\Status::WITH_BOOKING_LEARNER_ABSENT') %}
{% set status_progress =  constant('ApiBundle\\Entity\\Status::WITH_BOOKING_IN_PROGRESS') %}

{% set hour = module.duration|date('G', false) %}
{% set minutes = module.duration|date('i', false) %}
{% set duration = '' %}
{% set durationJs = '' %}
{% if hour == '0' %}
    {% set duration = '+'~minutes~' min' %}
    {% set durationJs = minutes %}
{% elseif minutes == '00' %}
    {% set duration = '+'~ hour ~ 'hours' %}
    {% set durationJs = hour * 60 %}
{% else %}
    {% set duration = '+' ~hour ~ ' hours' ~ ' +' ~ minutes~ ' min' %}
    {% set durationJs = minutes + hour * 60  %}

{% endif %}

<style>
    .bootstrap-select .dropdown-toggle .filter-option-inner{
        padding-right: unset;
        text-align: center;
    }
    #dashboard-learner .fc-view-container {
        overflow: hidden!important;
        max-height: unset!important;
    }
    .fc-cancelBooking-button{
        display: none;
    }
    .book-session .bootstrap-select .dropdown-toggle .filter-option-inner {
        color: #0076fe;
    }
    .book-session .bootstrap-select .dropdown-toggle .filter-option {
        border: 1px solid #0076fe!important;
        border-radius: 20px;
    }
    #online-calendar-modal .dm-radio-btn input:checked + span {
        color: white!important;
        background-color: #0076fe!important;
        width: 130px;
    }
    #online-calendar-modal .dm-radio-btn input + span {
        color: black!important;
        background-color: #e5f0fc!important;
        width: 130px;
    }
</style>
<div class="row" id="onlineSessionModule"
     data-id="{{ module.id }}"
     data-start="{{ module.beginningWithTime|date('Y-m-d H:i:s') }}"
     data-end="{{ module.endingWithTime|date('Y-m-d H:i:s') }}">
    <div class="col-md-4 pad-l-0" >
        <div class="col-md-12 row bg-white border-radius-10 marg-b-15 min-height-280 pad-t-15" >
            <div class="col-md-3 marg-b-10 text-center no-padding flex--center">
                <div class="flex--center btn-navy border-radius-50 no-padding" style="width: 50px; height: 50px;">
                    <object data="/images/online-white.svg" width="40" height="40"
                            type="image/svg+xml"></object>
                </div>
            </div>
            <div class="col-md-9 no-padding" >
                <span class="font-weight-600">{{ 'admin.interventions.mods.onlineseance'|trans }}</span>
                <h3  class="no-margin bold font-size-20 color-header">{{ module.designation }}</h3>
            </div>

            <div class="col-md-12 border-top pad-t-15 pad-r-0 pad-l-0 font-size-13 pad-b-15">
                <p class="no-margin font-weight-600" >{{ 'admin.skills.form.description_label'|trans }}</p>
                <div class="col-md-12 no-padding text-justify font-size-13" >
                    {{ module.description|raw }}
                </div>
            </div>

            <div class="col-md-12 no-padding row padding-bottom-15" >
                <div class="col-md-8 no-padding">
                    <p class="color-header no-margin bold" >
                        <embed src="/images/clock.svg" width="22" height="22"
                               type="image/svg+xml"/>&nbsp;&nbsp;&nbsp;&nbsp;<span class="font-size-20">{{ module.duration|date('H:i:s') }}</span>
                    </p>
                    <p class="no-margin">
                        <embed src="/images/calendar.svg" width="18" height="20"
                               type="image/svg+xml"/>&nbsp;&nbsp;&nbsp;<span class="font-size-13 text-gray">{{ module.beginning|date('d/m/Y') }} {{'global.to'|trans}} {{ module.ending|date("d/m/Y") }}</span>
                    </p>
                </div>
                <div class="col-md-4 no-padding text-center text-gray" >
                    {% if (module.minScore is not empty) %}
                        <span  class="font-weight-600 font-size-13">{{ 'learners.courses.score_to_pass'|trans|capitalize }}</span><br>
                        <span class="font-size-30 font-weight-800">{{ module.minScore  }}%</span>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-12 bg-white border-radius-10">
            <div class="col-md-12 text-center pad-15" >
                <span  class="font-weight-600 font-size-20 color-header">{{ 'learners.courses.documents'|trans }}</span>
            </div>
            <div class="col-md-12" >
                {% if module.educationalDocument|length != 0 %}
                    {{ include('molecules/tables/files-list.html.twig', {documents: module.educationalDocument, type: "documents"}) }}
                {% endif %}
            </div>
        </div>
    </div>
    <div id="dashboard-learner" class="col-md-8 no-padding">
        <div class="calendar-wrapper col-md-12 bg-white border-radius-10 pad-t-15 pad-b-15  height-auto {% if isBooked  %}d-none{% endif %} " data-target="calendar" >
            <div class="col-md-12 text-center padding-bottom-15">
                <h3 class="color-header font-weight-800 no-margin">
                    {{ 'popup.book_your_session'|trans|capitalize }}
                </h3>
                <div class="col-md-12 no-margin row form-group book-session">
                    <div class="col-md-4"></div>
                    <div class="text-center  col-md-4">
                        {% if assignments is defined %}
                            <select id="assignments" name="status" class="form-control selectpicker" data-style="btn btn-link">
                                <option value="">{{ 'global.any_trainer'|trans }}</option>
                                {% for assignment in assignments %}
                                    {% if assignment.liveResource is defined and assignment.liveResource is not empty %}
                                        <option value="{{ assignment.liveResource.id }}">{{ assignment.liveResource.displayName }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        {% endif %}
                    </div>
                    <div class="col-md-4"></div>
                </div>
            </div>

            {{ include('molecules/calendar/calendar-legend.twig', {user:'learner_booking'}) }}
            <div id="onlineSessionCalendar"></div>
        </div>
        {% if booked is defined and booked is not empty %}
            <div class="col-md-12  row bg-white border-radius-10 pad-t-15 pad-b-20 ">
                <div class="col-md-4 flex--center no-padding module text-left justify-content-none">
                    <span class="module-circle module-booked-status" ></span> &nbsp; &nbsp; <span class="font-weight-800 module-booked-status-color font-size-14">
                        {{ include('molecules/widgets/booking-status.html.twig', { appId: booked.status.appId }) }}&nbsp;!
                    </span>
                </div>
                <div class="col-md-4 flex--center text-center">
                    <span  class="color-header font-weight-600 font-size-20">{{ 'learners.courses.my_session'|trans }}</span>
                </div>

                <div class="col-md-4 text-right no-padding">
                    {% if route != 'trainer_exercices_video_booking_agenda' and booked.status.appId != status_done and booked.status.appId != status_absent and booked.status.appId != status_progress %}
                        {% if expired %}
                            <button style="font-size: 11px;" data-toggle="modal" href="#expire-info" class="btn width-auto btn-small btn-deepmark-red">{{ 'learners.courses.expire_booking' |trans }}</button>
                            {{ include('molecules/modal/expire-modal.html.twig') }}
                        {% else %}
                            <button id="cancel-booking-info" class="btn btn-sm btn-deepmark-red">{{ 'learners.courses.cancel_booking' |trans }}</button>
                        {% endif %}
                    {% elseif booked.status.appId == status_done %}
                        {% if isBooked %}
                            {{ include('molecules/courses/navigation.html.twig') }}
                            {% if canBeNotated %}
                                {{ include('molecules/courses/notation.html.twig') }}
                            {% endif %}
                        {% endif %}
                    {% endif %}
                </div>
                <div class="col-md-12 text-center marg-t-15">
                    <h2 class="bold no-margin">{{ booked.bookingDate|localizeddate('full', 'none', app.request.locale)|capitalize }}</h2>
                    <h3 class="no-margin font-weight-600 marg-bottom-20" > {{ booked.bookingDate|date('G:i', false) }} - {{ booked.bookingDate|date_modify(duration)|date('G:i', false) }} </h3>
                </div>
                {{ include('molecules/widgets/count-down-booking.html.twig') }}
                <div class="row col-md-12 pad-t-15 marg-t-30 text-white pad-b-15 backgroud-header">
                    <div class="col-2">
                        <i class="fa fa-user font-size-18"></i>
                    </div>
                    <div class="col-8 text-center ">
                        <p class="no-margin text-white text-uppercase font-size-18">{{ 'admin.interventions.create.step1.trainer' | trans }}</p>
                    </div>
                    <div class="col-md-2"></div>
                </div>
                <div class=" col-md-12 marg-b-15 text-center pad-t-15 text-white pad-b-15 backgroud-deepmark-light">
                    <p class="no-margin color-header font-size-18"> <b class="bold">{{ booked.trainer.entity.organisation.designation }}</b> - {{ booked.trainer.entity.designation }}</p>
                </div>
                <div class="col-md-3 text-center user-info-text">
                    {{ booked.trainer.firstName ~' '~booked.trainer.lastname }}
                </div>
                <div class="col-md-6 border-left-header text-center user-info-text">
                    {{ booked.trainer.person.email }}
                </div>
                <div class="col-md-3 text-center border-left-header">
                    {{ booked.trainer.mobilePhone }}
                </div>
                <div class="col-md-12 pad-t-30"></div>
            </div>
        {% endif %}

        {% if booked and (booked.status.appId == status_done or booked.status.appId == status_absent or expired) %}
            {{ include('molecules/widgets/synthesis.html.twig') }}
        {% endif %}
        <span id="cancel-booking-text" class="text-template">{{ 'learners.courses.cancel_booking'|trans }}</span>
        <span id="book-session-text" class="text-template">{{ 'learners.courses.book_session'|trans }}</span>

    </div>
</div>
{{ include('molecules/modal/online-calendar-modal.html.twig') }}
{{ include('molecules/modal/cancel-confirmation-modal.html.twig') }}

{% block javascripts %}
    <script src="{{ asset('js/learner/calendar-online.js') }}"></script>
{% endblock %}